name: Build Pipeline for Test
on:
  - pull_request
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '^1.21'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: run recursive test
      run: |
        set -e
        go test -v ./...
